AutoMobile.UI/AutoMobile.Web/Controllers/AuthController.cs
using AutoMobile.Application.Services.Interface;
using AutoMobile.Domain.Common;
using AutoMobile.Domain.DTO.User;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;
using AutoMobile.Domain.ApplicationConstants;
using AutoMobile.Domain.ViewModels.SelectListItemVM;
using Microsoft.AspNetCore.Mvc.Rendering;
using AutoMobile.Application.Services;
using Microsoft.AspNetCore.Http;
using System.Collections.Specialized;
using System.Web;
using AutoMobile.Domain.DTO.UserManager;
using System.Collections.Generic;
using System.Xml.Linq;

namespace AutoMobile.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly IJwtHelper _jwtHelper;

        public AuthController(IAuthService authService, IJwtHelper jwtHelper)
        {
            _authService = authService;
            _jwtHelper = jwtHelper;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDto loginRequestDto = new LoginRequestDto();

            return View(loginRequestDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDto loginRequestDto)
        {
            ApiResponse response = await _authService.LoginAsync<ApiResponse>(loginRequestDto);

            if (response != null && response.IsSuccess)
            {
                LoginResponseDto model = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(response.Result));

                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

                //Extract Role from Token
                var tokenData = _jwtHelper.ExtractTokenData(model.Token);

                identity.AddClaim(new Claim(ClaimTypes.Name, model.UserId));

                if (tokenData != null)
                {
                    identity.AddClaim(new Claim(ClaimTypes.Role, tokenData.Role.ToUpper()));

                    if(tokenData.AdditionalClaims.Count > 0)
                    {
                        foreach (var claim in tokenData.AdditionalClaims)
                        {
                            foreach (var claimValue in claim.Value)
                            {
                                identity.AddClaim(new Claim(claim.Key, claimValue));
                            }
                        }
                    }
                   
                }

                var principle = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principle, new AuthenticationProperties
                {
                    IsPersistent = true,
                    ExpiresUtc = DateTimeOffset.UtcNow.Add(TimeSpan.FromMinutes(30))
                });

                //HttpContext.Session.SetString(ApplicationConstant.SessionToken, model.Token);

                HttpContext.Response.Cookies.Append(ApplicationConstant.SessionToken, model.Token, new CookieOptions
                {
                    Expires = DateTimeOffset.UtcNow.Add(TimeSpan.FromMinutes(30)),
                    HttpOnly = true,
                    Secure = true,
                    SameSite = SameSiteMode.Strict
                });

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CustomError", response.Errors.FirstOrDefault().Description);
                return View(loginRequestDto);
            }
        }



        [HttpGet]
        public IActionResult Register()
        {
            RegisterationRequestDto registerationRequestDto = new RegisterationRequestDto();

            return View(registerationRequestDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterationRequestDto registerationRequestDto)
        {
            ApiResponse response = await _authService.RegisterAsync<ApiResponse>(registerationRequestDto);

            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(RegisterVerification));
            }
            else
            {
                ModelState.AddModelError("CustomError", response.Errors.FirstOrDefault().Description);
                return View(registerationRequestDto);
            }
        }


        public IActionResult RegisterVerification()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AdminRegister()
        {

            var response = await _authService.GetRolesAsync<ApiResponse>();

            if (response.IsSuccess)
            {
                List<string> roles = JsonConvert.DeserializeObject<List<string>>(Convert.ToString(response.Result));


                AdminRegisterVM adminRegisterVM = new AdminRegisterVM
                {
                    RegisterationRequestDto = new AdminRegisterationRequestDto(),
                    RolesList = roles.Order().Select(x => new SelectListItem
                    {
                        Text = x,
                        Value = x.ToString()
                    })
                };

                return View(adminRegisterVM);
            }

            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdminRegister(AdminRegisterationRequestDto registerationRequestDto)
        {
            ApiResponse response = await _authService.AdminRegisterAsync<ApiResponse>(registerationRequestDto);

            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "User Successfully Registered";

                return RedirectToAction(nameof(AdminRegister));
            }
            else
            {
                ModelState.AddModelError("CustomError", response.Errors.FirstOrDefault().Description);
                return View(registerationRequestDto);
            }
        }


        [HttpGet]
        public IActionResult EmailConfirmation()
        {
            return View();
        }

        [HttpPost, ActionName("EmailConfirmation")]
        public async Task<IActionResult> EmailConfirmationPost()
        {
            var queryString = HttpContext.Request.QueryString.ToString();

            //// Parse the query string
            //NameValueCollection queryParams = HttpUtility.ParseQueryString(queryString);

            //// Extract UserId and Token values
            //string userId = queryParams["UserId"];
            //string token = queryParams["Token"];

            var response = await _authService.EmailConfirmationAsync<ApiResponse>(queryString);

            if (response.IsSuccess)
            {
                return RedirectToAction(nameof(AccountVerified));
            }

            return View();
        }

        public IActionResult AccountVerified()
        {
            return View();
        }


        [HttpGet]
        public IActionResult ForgetPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgetPassword(string emailId)
        {
            var response = await _authService.ForgetPasswordAsync<ApiResponse>(emailId);

            if (response.IsSuccess)
            {
                return RedirectToAction(nameof(PasswordReset));
            }

            return View();
        }

        public IActionResult PasswordReset()
        {
            return View();
        }


        [HttpGet]
        public IActionResult ResetPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword(string newPassword)
        {
            var queryString = HttpContext.Request.QueryString.ToString() + $"&&newPassword={newPassword}";

            var response = await _authService.ResetPasswordAsync<ApiResponse>(queryString);

            if(response.IsSuccess) 
            { 
                return RedirectToAction(nameof(ResetPasswordSuccess));
            }

            return View();
        }

        [HttpGet]
        public IActionResult ResetPasswordSuccess()
        {
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            HttpContext.Response.Cookies.Delete(ApplicationConstant.SessionToken);

            return RedirectToAction("Login");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
        public IActionResult InternalServerError()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetUsers()
        {
            List<ApplicationUserDto> applicationUserDtos = new List<ApplicationUserDto>();

            var response = await _authService.GetUsersAsync<ApiResponse>();

            if (response !=null && response.IsSuccess)
            {
                applicationUserDtos = JsonConvert.DeserializeObject<List<ApplicationUserDto>>(Convert.ToString(response.Result));

                return View(applicationUserDtos);
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ChangeUserRole(string id)
        {
            ApplicationUserDto userDto = new ApplicationUserDto();

            var response = await _authService.GetUserByIdAsync<ApiResponse>(id);

            if(response != null && response.IsSuccess)
            {
                userDto = JsonConvert.DeserializeObject<ApplicationUserDto>(Convert.ToString(response.Result));

                return View(userDto);
            }

            return View();
        }

        [HttpPost]

AutoMobile.UI/AutoMobile.Web/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutoMobile.Web.Controllers
{
    [Authorize]
    public class ManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult JuniorManager()
        {
            return View();
        }

        public IActionResult SeniorManager()
        {
            return View();
        }

        public IActionResult AssistantManager()
        {
            return View();
        }

        public IActionResult AssociateProductManager()
        {
            return View();
        }
    }
}

AutoMobile.UI/AutoMobile.Web/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace AutoMobile.Web.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult LoadPage(string pageName)
        {
            // Handle the logic to determine which page to load based on the 'pageName' parameter
            // Render the corresponding partial view and return it
            return PartialView($"_{pageName}"); // Assuming partial views are named with an underscore prefix (e.g., "_Home.cshtml")
        }
    }
}

AutoMobile.UI/AutoMobile.Web/Controllers/VehicleController.cs
using AutoMapper;
using AutoMobile.Application.Services.Interface;
using AutoMobile.Domain.ApplicationConstants;
using AutoMobile.Domain.Common;
using AutoMobile.Domain.DTO.Vehicle;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using static AutoMobile.Application.ApplicationContants.ApplicationConstant;

namespace AutoMobile.Web.Controllers
{
    public class VehicleController : Controller
    {

        private readonly IVehicleService _vehicleService;
        private readonly IMapper _mapper;
        public VehicleController(IVehicleService vehicleService, IMapper mapper)
        {
            _vehicleService = vehicleService;
            _mapper = mapper;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            List<VehicleDto> list = new List<VehicleDto>();

            var token = Request.Cookies[ApplicationConstant.SessionToken];

            var response = await _vehicleService.GetAllAsync<ApiResponse>(token);

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VehicleDto>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [HttpGet]
        [Authorize(Roles = CustomRole.SuperAdmin + "," + CustomRole.MasterAdmin + "," + CustomRole.Admin + "," + CustomRole.PremiumUser)]
        public async Task<IActionResult> Details(int id)
        {
            var token = Request.Cookies[ApplicationConstant.SessionToken];

            var response = await _vehicleService.GetAsync<ApiResponse>(id, token);

            if (response != null && response.IsSuccess)
            {
                VehicleDetailsDto model = JsonConvert.DeserializeObject<VehicleDetailsDto>(Convert.ToString(response.Result));

                return View(model);
            }

            return NotFound();
        }

        [HttpGet]
        [Authorize(Roles = CustomRole.SuperAdmin + "," + CustomRole.MasterAdmin + "," + CustomRole.Admin)]
        public IActionResult Create()
        {
            VehicleCreateDto vehicleCreateDto = new VehicleCreateDto();

            return View(vehicleCreateDto);
        }

        [HttpPost]
        [Authorize(Roles = CustomRole.SuperAdmin + "," + CustomRole.MasterAdmin + "," + CustomRole.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VehicleCreateDto dto)
        {
            if (ModelState.IsValid)
            {
                var token = Request.Cookies[ApplicationConstant.SessionToken];

                var response = await _vehicleService.CreateAsync<ApiResponse>(dto, token);

                if (response != null && response.IsSuccess)
                {

                    TempData["success"] = response.DisplayMessage;

                    return RedirectToAction(nameof(Index));
                }

            }

            return View(dto);
        }

        [HttpGet]
        [Authorize(Roles = CustomRole.SuperAdmin + "," + CustomRole.MasterAdmin)]
        public async Task<IActionResult> Update(int id)
        {
            var token = Request.Cookies[ApplicationConstant.SessionToken];

            var response = await _vehicleService.GetAsync<ApiResponse>(id, token);

            if (response != null && response.IsSuccess)
            {
                VehicleDetailsDto model = JsonConvert.DeserializeObject<VehicleDetailsDto>(Convert.ToString(response.Result));

                return View(_mapper.Map<VehicleUpdateDto>(model));
            }

            return View();
        }

        [HttpPost]
        [Authorize(Roles = CustomRole.SuperAdmin + "," + CustomRole.MasterAdmin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(VehicleUpdateDto dto)
        {
            if (ModelState.IsValid)
            {
                var token = Request.Cookies[ApplicationConstant.SessionToken];

                var response = await _vehicleService.UpdateAsync<ApiResponse>(dto, token);

                if (response != null && response.IsSuccess)
                {

                    TempData["success"] = response.DisplayMessage;

                    return RedirectToAction(nameof(Index));
                }

            }

            return View(dto);
        }

        [HttpGet]
        [Authorize(Roles = CustomRole.SuperAdmin)]
        public async Task<IActionResult> Delete(int id)
        {
            var token = Request.Cookies[ApplicationConstant.SessionToken];

            var response = await _vehicleService.GetAsync<ApiResponse>(id, token);

            if (response != null && response.IsSuccess)
            {
                VehicleDetailsDto model = JsonConvert.DeserializeObject<VehicleDetailsDto>(Convert.ToString(response.Result));

                return View(_mapper.Map<VehicleUpdateDto>(model));
            }

            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = CustomRole.SuperAdmin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(VehicleDetailsDto dto)
        {
            if (ModelState.IsValid)
            {
                var token = Request.Cookies[ApplicationConstant.SessionToken];

                var response = await _vehicleService.DeleteAsync<ApiResponse>(dto.Id, token);

                if (response != null && response.IsSuccess)
                {

                    TempData["success"] = response.DisplayMessage;

                    return RedirectToAction(nameof(Index));
                }

            }

            return View(dto);
        }

    }
}

AutoMobile.UI/AutoMobile.Web/Views/Shared/_Annually.cshtml
<h1>Annually</h1>

AutoMobile.UI/AutoMobile.Web/Views/Shared/_Layout.cshtml
@using static AutoMobile.Application.ApplicationContants.ApplicationConstant;
@{
    string[] roles = { CustomRole.SuperAdmin, CustomRole.MasterAdmin, CustomRole.Admin };

    bool isInMultipleRoles = roles.Any(role => User.IsInRole(role));
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoMobile.Web</title>
    <link rel="stylesheet" href="~/css/Bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutoMobile.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sidebars/">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow" data-bs-theme="dark">
            <div class="container-fluid">
                <button class="navbar-toggler bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Vehicle" asp-action="Index">Vechiels</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Manager" asp-action="Index">Manager</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="EmployeeBenefits">Employee Benefits</a>
                        </li>
                        @if (User.IsInRole(CustomRole.SuperAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="text-warning nav-link  dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Manage User</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Auth" asp-action="AdminRegister">Register User</a>
                                    <a class="dropdown-item" asp-controller="Auth" asp-action="GetUsers">Users</a>
                                    
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-dark footer text-muted">
        <div class="container text-light text-center">
            &copy; 2023 - AutoMobile Top Speed - By Karthik
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AutoMobile.UI/AutoMobile.Web/Views/Shared/_Monthly.cshtml
<h1>Monthly</h1>

AutoMobile.UI/AutoMobile.Web/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 1500,
        })
    </script>
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 1500,
        })
    </script>
}

AutoMobile.UI/AutoMobile.Web/Views/Shared/_Overview.cshtml
<h1>OverView</h1>

AutoMobile.UI/AutoMobile.Web/Views/Shared/_Updates.cshtml
<h1>Updates</h1>

AutoMobile.UI/AutoMobile.Web/Views/Shared/_Weekly.cshtml
<h1>Weekly</h1>